
import { NavItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: { en: 'Home', nl: 'Home' }, path: '/' },
  { label: { en: 'Services', nl: 'Diensten' }, path: '/services' },
  { label: { en: 'Tools', nl: 'Tools' }, path: '/tools' },
  { label: { en: 'Market Insights', nl: 'Chartering Advisory' }, path: '/insights' },
  { label: { en: 'Pricing', nl: 'Tarieven' }, path: '/pricing' },
  { label: { en: 'About Us', nl: 'Over Ons' }, path: '/about' },
  { label: { en: 'Contact', nl: 'Contact' }, path: '/contact' },
];

export const TRANSLATIONS = {
  en: {
    heroTitle: 'Independent Freight Validation & Market Insight.',
    heroSubtitle: 'Mitigate chartering risks and secure fair shortsea rates across Europe. We are not a shipbroker and earn no commissions. Get objective data before you fix.',
    heroPricingNote: 'Basic indications and tools are complimentary. Detailed validation reports are provided at fixed fees.',
    ctaPrimary: 'Indicative Freight Range',
    ctaSecondary: 'Request Advice',
    ctaOfferCheck: 'Validate Broker Offer',
    ctaServices: 'Service Overview',
    formTitle: 'Request Freight Indication',
    formSubtitle: 'This module provides an indicative market range benchmark. Use this to set realistic rate expectations before approaching the market.',
    cargoLabel: 'Cargo Description (e.g., Steel Coils, Grain)',
    volumeLabel: 'Volume (Metric Tons)',
    loadLabel: 'Loading Port',
    dischLabel: 'Discharging Port',
    submitButton: 'Calculate Indicative Estimate',
    loading: 'Calculating Market Benchmark...',
    resultTitle: 'Voyage Indication',
    advisoryTitle: 'Strategic Market Advisory',
    rateUnit: 'per metric ton',
    distance: 'Distance',
    nm: 'nautical miles',
    disclaimer: 'This is an indicative market benchmark based on current algorithms, not a binding offer.',
    servicesTitle: 'European Shortsea Support',
    servicesText: 'Independent validation and decision support for the intra-European transport of dry bulk and breakbulk.',
    service1Title: 'Spot Chartering Insights',
    service1Text: 'Objective validation of single-voyage offers across all European ports.',
    service2Title: 'COA Analysis',
    service2Text: 'Risk and cost assessment for long-term volume contracts and fixed-pricing commitments.',
    service3Title: 'Project Cargo Validation',
    service3Text: 'Specialized review for oversized or heavy-lift transport requirements.',
    service4Title: 'Compliance & Exposure',
    service4Text: 'Monitoring adherence to international standards and environmental cost modeling.',
    service5Title: 'Logistics Risk Review',
    service5Text: 'Assessing operational bottlenecks and integrated shortsea route risks.',
    serviceFreightTitle: 'Freight Benchmarking',
    serviceFreightText: 'Data-driven freight indications to establish market ranges for your desired route.',
    serviceAnalyzerTitle: 'Quote Validation',
    serviceAnalyzerText: 'Professional risk and commercial analysis of broker quotes against independent market data.',
    servicesCtaTitle: 'Strengthen your chartering position.',
    servicesCtaText: 'Access objective data points to improve your shipping terms before finalizing your charter.',
    servicesCtaButton: 'Get in Touch',
    insightsTitle: 'Chartering Advisory & Market Data',
    insightsText: 'Validate received quotes, monitor risk exposure, and track independent market benchmarks.',
    
    // Homepage Strategy Scan Dashboard
    targetRateTitle: 'Charterer Target Rate (PMT)',
    idealFixingTarget: 'Ideal Fixing Target',
    idealFixingDesc: 'Aim for this rate for the best commercial balance.',
    costTransparency: 'Cost Transparency (PMT)',
    marketBaseRate: 'Market Base Rate',
    bunkerFactor: 'Bunker Factor',
    liveBunkerBench: 'Live LSMGO Benchmark',
    externalFactors: 'External Factors',
    weatherSeasonal: 'Weather/Seasonal',
    portCanalFees: 'Port & Canal Fees',
    totalPmtEstimate: 'TOTAL PMT ESTIMATE',
    strategyAdvice: 'Charterer Strategy Advice',
    co2Threshold: 'CO2 Threshold',
    routeStatus: 'Route Status',
    trend30Days: '30-Day Trend',
    lastMatch: 'Last match',
    yourLeverage: 'Your Leverage',
    negotiationDesk: 'Charterer Negotiation Desk',
    tacticalPushback: 'Tactical Pushback Points',
    estVoyage: 'Est. Voyage',
    seaDistance: 'Sea Distance',
    shortest: 'SHORTEST',
    noCanal: 'NO KANAAL',
    viaKiel: 'Via Kiel Canal',
    viaSkagen: 'Via Skagen',
    recalculateRoute: 'Update Indication',
    exportStrategy: 'Export Strategy',

    vp1Title: 'QUOTE VALIDATION',
    vp1Text: 'Submit your broker quote for independent risk review. We verify terms, pricing, and market alignment.',
    vp2Title: 'MARKET BENCHMARKING',
    vp2Text: 'Access objective rate ranges and historical data to see what is fair for your specific route.',
    vp3Title: 'DATA-DRIVEN NEGOTIATION',
    vp3Text: 'Enter negotiations with concrete data points to improve your commercial shipping terms.',
    vp4Title: 'PURE INDEPENDENCE',
    vp4Text: 'Shortsea Europe is not a broker. We earn zero commission, ensuring 100% objective analysis.',
    
    processTitle: 'Validation in 3 Steps',
    step1HomeTitle: 'Receive a Quote',
    step1HomeDesc: 'Obtain an offer from your broker for a coaster or minibulker vessel.',
    step2HomeTitle: 'We Validate',
    step2HomeDesc: 'Upload the details for an independent commercial and risk analysis.',
    step3HomeTitle: 'Fix with Confidence',
    step3HomeDesc: 'Make your final chartering decision backed by objective market data.',

    // Advisory UI
    advTabTrends: 'Market Benchmarks',
    advTabAnalyzer: 'Quote Analyzer',
    advTabDocs: 'Standard Documents',
    advAnalyzerTitle: 'Professional Quote Validation',
    advAnalyzerSubtitle: 'Commercial and risk review of received offers. We operate independently of brokerage commissions.',
    advAnalyzerPlaceholder: 'Paste the broker quote text here (e.g., vessel name, rate, laycan, terms)...',
    advAnalyzerPricingNote: 'Validation services are provided at fixed fees. No brokerage commission is involved.',
    advUploadPdf: 'Upload PDF Quote',
    advFileSelected: 'PDF Attached: ',
    advOptionA: 'AI Quick Scan',
    advOptionADesc: 'Instant data-driven validation. Fixed fee service.',
    advOptionB: 'Expert Review',
    advOptionBDesc: 'In-depth manual review by experienced chartering professionals. Fixed fee service.',
    advBtnAnalyze: 'Start Validation Scan',
    advBtnExpert: 'Submit for Expert Review',
    advSuccessPending: 'Request submitted for expert validation. We do not participate in fixing; results are purely for decision support.',
    miUpdateBtn: 'Fetch Latest Benchmarks',
    
    // Gatekeeping & CTA
    advRegisterToView: 'Please log in for free to view the full report',
    advUpgradePro: 'Upgrade to Professional for unlimited detailed scans',
    advMonthlyLimit: 'Monthly free report limit reached',

    // Tile Labels
    tileAvgFreight: 'Market Avg',
    tileAvailability: 'Vessel Supply',
    tileDeepDive: 'Expert Analysis',
    regionBaltic: 'Baltic Sea',
    regionNorthSea: 'North Sea / UKC',
    regionMed: 'Mediterranean Sea',
    regionBlackSea: 'Black Sea',

    // Regional Highlights (Translations)
    hlBaltic1: 'Ice restrictions monitoring active in Kemi.',
    hlBaltic2: 'Baltic grain export exposure increasing.',
    hlNorthSea1: 'Port congestion alerts for major UKC hubs.',
    hlNorthSea2: 'Steel coil demand validation stable.',
    hlMed1: 'High activity levels in East Med ports.',
    hlMed2: 'Bunker exposure monitoring for Algeciras.',
    hlBlackSea1: 'Risk premiums and insurance validation required.',
    hlBlackSea2: 'Operational stability monitoring for Constanta.',

    // Trend Labels
    trendStable: 'Stable',
    trendFirm: 'Firming',
    trendSoft: 'Softening',

    // Trial
    trialRemaining: 'Trial ends in {{days}} days',
    trialExpired: 'Trial expired - Access Professional Insights',

    // How It Works
    hiwTitle: 'The Validation Process',
    hiwSubtitle: 'Independent decision support made simple and transparent.',
    step1Title: 'Indicate',
    step1Desc: 'Enter cargo specs to establish an initial market rate range.',
    step2Title: 'Analyze',
    step2Desc: 'Use tools to assess operational exposure and route risks.',
    step3Title: 'Validate',
    step3Desc: 'Submit your broker quote for an independent AI or Expert review.',
    step4Title: 'Fix',
    step4Desc: 'Finalize your deal with your broker, backed by objective data.',
    hiwCta: 'Start Benchmarking',

    // Contact
    contactTitle: 'Inquiry Desk',
    contactIntro: 'Contact our support team for specialized validation or account inquiries.',
    contactHq: 'Operations',
    contactPhone: 'Inquiry Line',
    contactEmail: 'Email',
    contactFormTitle: 'Send a Message',
    formFirstName: 'First Name',
    formFirstNamePlaceholder: 'John',
    formLastName: 'Last Name',
    formLastNamePlaceholder: 'Doe',
    formCompany: 'Company',
    formEmail: 'Email Address',
    formMessage: 'Inquiry Details',
    formSend: 'Send Message',

    // Request Offer
    roTitle: 'Expert Review Request',
    roSubtitle: 'Provide the voyage details for a hand-crafted professional validation report.',
    roSuccess: 'Request received. Our experts will analyze your file independently of brokerage interests.',
    roSectionVoyage: 'Voyage Details',
    roLaycanStart: 'Laycan Start',
    roLaycanEnd: 'Laycan End',
    roSectionCargo: 'Cargo Specification',
    roStowage: 'Stowage Factor',
    roHazmat: 'Special Requirements',
    roSectionTerms: 'Terms',
    roSectionContact: 'Contact Info',
    roTerms: 'Charter Terms',
    roIdea: 'Target Rate for Validation',
    roSubmit: 'Request Professional Report',

    // Pricing
    pricingTitle: 'Account Plans',
    pricingSubtitle: 'Objectivity is our value. We provide independent insight without brokerage commissions.',
    planFree: 'Standard Access',
    mo: '/ mo',
    feat1: 'Limited daily indications',
    feat2: 'Basic market benchmark data',
    feat3: 'Standard operational tools',
    feat4: 'Unlimited benchmarking',
    feat5: 'Full decision-support toolkit',
    feat6: 'Premium regional intelligence',
    feat7: 'Strategic support desk',
    feat8: 'Enterprise integrations',
    featAiScanPay: 'AI Quick Scan: €15 per check (Pay-per-scan)',
    featNoExpert: 'No access to Expert Review',
    featAiScanUnlim: 'Unlimited AI Quick Scans (Value €15 per scan)',
    featExpertAddon: 'Expert Review Add-on: €195 per check (Reduced rate)',
    featExpertIncl: 'Includes 2 Expert Reviews per month',
    featExpertPriority: 'Priority on manual dossier reviews',
    pricingSaveBadge: 'Save instantly: The AI Quick Scan validates your broker quotes for market compliance and risks. Professional users scan unlimited at no extra cost.',
    btnStart: 'Establish Access',
    btnContact: 'Contact Operations',
    planPro: 'Professional',
    planEnt: 'Enterprise',

    // About
    aboutTitle: 'Shortsea Europe Independence',
    aboutSubtitle: 'Restoring transparency to maritime chartering through objective validation.',
    abPartnerTitle: 'WHY SHORTSEA EUROPE?',
    abReliablePartnerTitle: 'Your Reliable Partner',
    abReliablePartnerText: 'Having worked as a charterer for over 20 years, I know firsthand the need for practical, independent tools for cargo owners. I created Shortsea Europe to bridge this gap, helping you communicate more effectively with your broker. Our platform allows you to validate offers and advice objectively, providing you with the data and counterarguments needed to strengthen your position. Navigate your negotiations with confidence, backed by professional insight.',
    abBullet1: 'Driven by Master Mariners',
    abBullet2: 'Independent & Transparent',
    abBullet3: 'Full Digital Integration',
    abImp1: 'Better Terms',
    abImp2: 'Reduced Risk',
    abImp3: 'Rate Accuracy',
    aboutTitle_full: 'About Shortsea Europe',
    abWhatIsTitle: 'Core Principles',
    abWhatIsText: 'Objectivity and transparency are at the core of our decision support platform.',
    abWhatIs1: 'Independence: No brokerage commissions.',
    abWhatIs2: 'Validation: Data-driven offer checks.',
    abWhatIs3: 'Independence: No brokerage commissions.',
    abWhatIs4: 'Integrity: Working for the charterer.',
    abAiTitle: 'Data-Driven',
    abAiText: 'Utilizing advanced algorithms for real-time market benchmarking.',
    abProcessTitle: 'Objective Review',
    abProcessText: 'From indication to validation without commercial conflict.',
    abSafeTitle: 'Compliant & Secure',
    abSafeText: 'Independently aligned with EU environmental and data regulations.',
    abGreenTitle: 'Sustainable Insights',
    abGreenText: 'Helping you navigate environmental exposure and ETS costs objectively.',

    // Tools
    toolDist: 'Distance Engine',
    toolDistDesc: 'Standard maritime sea distances for planning.',
    toolStow: 'Stowage Utility',
    toolStowDesc: 'Indicative conversion of stowage factors.',
    toolLay: 'Laytime Utility',
    toolLayDesc: 'Independent calculation of settlement risks.',
    toolIce: 'Ice Restriction Monitor',
    toolIceDesc: 'Indicative ice status for Baltic planning.',
    toolDA: 'Port Costs (D/A)',
    toolETS: 'ETS Exposure Monitor',
    toolETSDesc: 'Indicative CO2 cost assessment for EU ports.',
    toolsTitle: 'Decision Support Tools',
    toolsSubtitle: 'Indicative calculation tools to support European shortsea professionals.',
    btnUse: 'Open Tool',
    trustedBy: 'Independent insight for European chartering professionals',

    // Compliance
    compTitle: 'Standards & Integrity',
    compSubtitle: 'Our commitment to data objectivity and regulation.',
    compIntro: 'Shortsea Europe maintains absolute independence from shipowners and brokers to ensure unbiased decision support.',
    compGdprTitle: 'Data Integrity',
    compGdpr1: 'Encryption for all charterer data.',
    compGdpr2: 'No sharing of inquiries with commercial third-parties.',
    compGdpr3: 'User control over all stored validation history.',
    compMarTitle: 'Regulatory Alignment',
    compMar1: 'EU MRV reporting benchmarks.',
    compMar2: 'Objective EU ETS cost modeling.',
    compMar3: 'BIMCO standard clause monitoring.',
    compDigTitle: 'Platform Reliability',
    compDig1: 'Secure access protocols.',
    compDig2: 'Regular independent audits.',
    compDig3: 'Reliable market data sources.',
    compEnvTitle: 'Environmental Assessment',
    compEnv1: 'Indicative emission modeling.',
    compEnv2: 'Bunker efficiency benchmarks.',
    compEnv3: 'Green corridor exposure tracking.',
    compFooter: 'Systems are updated to reflect the latest European maritime regulations.',

    // Cookie Settings
    cookieTitle: 'Cookie Settings',
    cookieIntro: 'Shortsea Europe uses cookies and similar technologies (such as localStorage) to ensure the platform\'s functionality and improve your user experience.',
    cookieFuncTitle: 'Functional Technologies (Necessary)',
    cookieFuncText: 'We use local storage to save the results of market scans and route indications (such as routes from Tartous to Luleå) on your Chartering Advisory page. Without this technology, data would disappear with every page load.',
    cookieAnalyticTitle: 'Analytical Cookies',
    cookieAnalyticText: 'We may track anonymized statistics about how our tools are used to improve the speed and accuracy of our AI models (Gemini Pro/Flash).',
    cookieManageTitle: 'Management',
    cookieManageText: 'You can determine which cookies you accept through these settings or via your browser settings. Please note: disabling functional cookies may lead to the loss of stored calculations on your dashboard.',
    cookieEprivacyTitle: 'Cookie Policy & Transparency',
    cookieStrictTitle: 'Strict Necessity',
    cookieStrictText: 'We use localStorage to remember your "Chartering Advisory" data after a manual scan by the Admin. According to the EU ePrivacy Directive, no prior consent is required for this functional storage, provided it is essential for the service requested by the user.',
    cookieNoTrackTitle: 'No Third-Party Tracking',
    cookieNoTrackText: 'Shortsea Europe does not sell your search behavior (such as routes from Tartous to Luleå) to third-party advertising networks.',
    cookiePrefTitle: 'Preference Management',
    cookiePrefText: 'Users can adjust their preferences for analytical tools at any time via this menu.',

    // Privacy Policy
    privacyTitle: 'Privacy Policy',
    privacyIntro: 'At Shortsea Europe, we take the protection of your data seriously. This privacy policy explains how we handle information on our Chartering Advisory page and other parts of our platform.',
    privacyCollTitle: 'Data Collection',
    privacyCollText: 'We only collect data necessary for generating maritime advice, such as load/discharge ports, cargo types, and volumes.',
    privacyAiTitle: 'Use of AI and Data',
    privacyAiText: 'Our website uses advanced AI models and websearch technology to analyze live market data, bunker prices, and navigation routes. This data is used to provide the user with intelligent market insights.',
    privacyStoreTitle: 'Data Storage',
    privacyStoreText: 'For your convenience, we use local storage (localStorage) in your browser. This ensures that the latest market analyses and route calculations remain visible on your screen, even after refreshing the page, until a new scan is performed by the administrator.',
    privacySecTitle: 'Security',
    privacySecText: 'We implement strict technical measures to prevent unauthorized access to our systems and your search history.',
    privacyRightsTitle: 'User Rights',
    privacyRightsText: 'You have the right to clear your local browser data through your browser settings.',
    privacyGdprTitle: 'AVG / GDPR Statement',
    privacyGdprLegalTitle: 'Legal Basis',
    privacyGdprLegalText: 'We process data based on legitimate interest for the execution of maritime analyses and quotes.',
    privacyGdprAccessTitle: 'Right to Inspection and Deletion',
    privacyGdprAccessText: 'In accordance with EU legislation, you have the right to view, correct or have your data removed from our local systems.',
    privacyGdprEuStorageTitle: 'Data Storage within the EU',
    privacyGdprEuStorageText: 'We strive to keep data processing within the European Economic Area (EEA) as much as possible. Where AI models outside the EEA are used, this occurs under strict security protocols.',
    privacyGdprAutoTitle: 'Automated Decision Making',
    privacyGdprAutoText: 'Our website uses algorithms for market figures such as "Market Avg" and "Vessel Supply". These are indicative only and do not constitute a legally binding automated decision.',

    // EU Compliance Page
    euCompTitle: 'EU Compliance Framework',
    euCompIntro: 'Shortsea Europe is fully committed to adhering to European regulatory standards, including GDPR and ePrivacy directives.',

    // Legal Disclaimer
    legalDisclaimerTitle: 'MARITIME DISCLAIMER (EU COMPLIANT)',
    legalDisclaimerText: 'The displayed routes, including the Skagen alternative (dashed line), are AI-generated simulations for commercial analysis purposes. This data does not meet SOLAS/IMO requirements for navigation. Use for navigation is strictly prohibited and is at your own risk. Shortsea Europe accepts no liability for nautical incidents or financial losses resulting from the use of this information.',

    // Terms of Service
    tosTitle: 'Terms and Service - Shortsea Europe',
    tos1Title: '1. Acceptance of Terms',
    tos1Text: 'By using the website and services of Shortsea Europe, you agree to these Terms and Conditions. These terms apply to all users, including charterers, shipowners, and cargo owners.',
    tos2Title: '2. Informational Services (No Guarantee)',
    tos2Text: 'Shortsea Europe provides logistics intelligence, freight rate indications, and navigation routes based on artificial intelligence (AI) and external market data. All data provided (including freight rates, fuel costs, ETS calculations, and routes) is intended solely for informational purposes. Shortsea Europe in no way guarantees the accuracy, completeness, or timeliness of the information provided. Use of this data is entirely at the user\'s own risk.',
    tos3Title: '3. Limitation of Liability (Indemnification)',
    tos3Text: 'Shortsea Europe, its owners, and employees shall under no circumstances be held liable for: Navigation errors, Financial loss, or Operational delays.',
    tos3NavTitle: 'Navigation Errors',
    tos3NavText: 'Although our systems are programmed to simulate safe maritime routes, these should never be used for actual onboard navigation. Final route planning is the exclusive responsibility of the Master and the shipping company.',
    tos3FinTitle: 'Financial Loss',
    tos3FinText: 'We are not liable for indirect damage, consequential damage, lost profits, or missed savings resulting from decisions made based on our market figures or advice.',
    tos3OpTitle: 'Operational Delays',
    tos3OpText: 'We accept no liability for costs resulting from ice restrictions, port congestion, or canal passages that deviate from our indications.',
    tos4Title: '4. Intellectual Property',
    tos4Text: 'The unique software architecture, route logic, and interface of Shortsea Europe are the property of the website owner. Copying, reverse-engineering, or unauthorized distribution of our data and code is strictly prohibited.',
    tos5Title: '5. Changes and Availability',
    tos5Text: 'Shortsea Europe reserves the right to change or discontinue services at any time without prior notice. We are not liable for technical failures or temporary unavailability of the website.',
    tos6Title: '6. Applicable Law',
    tos6Text: 'Dutch law applies to these conditions and all disputes arising from the use of Shortsea Europe. Disputes will be submitted exclusively to the competent court in the district where the owner of the website is located.',

    // Standard texts
    freightIndicationTitle: 'FREIGHT RATE BENCHMARK (PMT)',
    lowEstimate: 'MARKET LOW',
    highEstimate: 'MARKET HIGH',
    estimateDisclaimer: 'Indicated rates are market benchmarks for support only.',
    proceedToFirm: 'VALIDATE YOUR RECEIVED OFFER',
    reqFirmOffer: 'Request Validation Report',
    calculationBasis: 'Based on independent market averages and maritime paths.',
    prop1Title: 'Instant Validation',
    prop1Text: 'Establishing rate benchmarks in seconds.',
    prop2Title: 'Independent Data',
    prop2Text: 'Derived from verified fixtures and live bunker data.',
    prop3Title: 'Objective Network',
    prop3Text: 'Broad coverage across European coaster vessel supply.',
    prop4Title: 'Integrity Guarantee',
    prop4Text: 'Absolute independence from brokerage and commissions.',
    ctaSecondary_nav: 'Request Advice',
    footerText: 'Independent decision support for the modern charterer.',
    footerPlatform: 'Platform',
    footerCompany: 'Operations',
    footerServices: 'Validation',
    footerInsights: 'Market Intel',
    footerPricing: 'Access',
    footerAbout: 'Independence',
    footerContact: 'Inquiry',
    footerRights: 'All rights reserved.',
    miRegional: 'Regional Intel',
    miBunkers: 'Bunker Benchmarks',
    miCargo: 'Cargo Indicators',
    miLastUpdate: 'Benchmark Sync',
    miDriver: 'Primary Market Driver',

    // Dashboard Keys
    dbWelcome: 'Welcome back, {{name}}',
    dbSummary: 'You have {{msgCount}} messages and {{advCount}} active advisory dossiers.',
    dbNewScan: 'New AI Scan',
    dbReqAdvice: 'Request Expert Advice',
    dbReqExpert: 'Request Expert Review',
    dbTotalScans: 'Total AI Scans',
    dbExpertReports: 'Expert Reports',
    dbHqMessages: 'HQ Messages',
    dbRecentScans: 'Recent Scans',
    dbViewAll: 'View All',
    dbNoScans: 'No recent scans.',
    dbHqNotifs: 'HQ Notifications',
    dbInbox: 'Inbox',
    dbNoMsgs: 'No new messages.',
    dbScanHist: 'AI Validation History',
    dbScanHistDesc: 'History of all instant AI Quick Scans performed on this account.',
    dbColDate: 'Date',
    dbColQuote: 'Quote / Reference',
    dbColStatus: 'Status',
    dbColAction: 'Action',
    dbStatusComp: 'Completed',
    dbViewAdvice: 'View Advice',
    dbExpertDossiers: 'Expert Dossiers',
    dbNoDossiers: 'No dossiers.',
    dbCharterAdvice: 'Vessel Chartering Advice',
    dbDossier: 'Dossier',
    dbReviewProgress: 'Expert Review in Progress',
    dbReviewDesc: 'Our brokers are analyzing your quote against current market fixtures. You will be notified once released.',
    dbHqDash: 'HQ Advisory Dashboard',
    dbSelectDossier: 'Select a dossier from the sidebar to view detailed expert analysis and market risks.',
    dbHqComm: 'HQ Communications Center',
    dbHqCommDesc: 'Direct messages and system updates from Shortsea Europe HQ.',
    dbInboxEmpty: 'Inbox Empty',
    dbAccountMember: 'Account Member',
    dbCompany: 'Company Name',
    dbEmail: 'Email Address',
    dbMemberSince: 'Member Since',
    dbVerifyStatus: 'Verification Status',
    dbVerified2fa: 'Verified 2FA',
    dbEncryptedNote: 'Personal profile data is encrypted using Shortsea Pro security protocols. Contact HQ to update company details.',
    dbTerminate: 'Terminate Session',
    dbPortalTitle: 'Client Portal',
    dbPortalSubtitle: 'Shortsea Europe Control',
    dbSignOut: 'Sign Out',
    dbArchiveTitle: 'AI Quick Scan Archive',
    dbRef: 'Reference',
    dbOrigQuote: 'Original Input Quote',
    dbCloseArchive: 'Close Archive',
    dbNavOverview: 'Overview',
    dbNavScans: 'AI Scans',
    dbNavAdvisory: 'Advisory',
    dbNavMessages: 'HQ Messages',
    dbNavProfile: 'Account Profile'
  },
  nl: {
    heroTitle: 'Onafhankelijke Vrachtvalidatie & Marktinzicht.',
    heroSubtitle: 'Beperk bevrachtingsrisico\'s en waarborg marktconforme tarieven door heel Europa. Wij zijn geen broker en ontvangen geen commissies. Objectieve data vóórdat u een schip fixeert.',
    heroPricingNote: 'Basisindicaties en tools zijn kosteloos. Gedetailleerde validatierapporten zijn beschikbaar tegen vaste tarieven.',
    ctaPrimary: 'Vrachtrange Indiceren',
    ctaSecondary: 'Advies Aanvragen',
    ctaOfferCheck: 'Offerte Valideren',
    ctaServices: 'Dienstenoverzicht',
    formTitle: 'Vrachtrange Indicatie',
    formSubtitle: 'Deze module biedt een onafhankelijke marktbenchmark. Gebruik dit om realistische tariefverwachtingen te scheppen.',
    cargoLabel: 'Ladingomschrijving (bijv. Staalrollen, Graan)',
    volumeLabel: 'Volume (Metrieke Ton)',
    loadLabel: 'Laadhaven',
    dischLabel: 'Los-haven',
    submitButton: 'Bereken Marktbenchmark',
    loading: 'Benchmark Berekenen...',
    resultTitle: 'Reisindicatie',
    advisoryTitle: 'Strategisch Marktadvies',
    rateUnit: 'per metrieke ton',
    distance: 'Afstand',
    nm: 'zeemijl',
    disclaimer: 'Dit betreft een indicatieve marktbenchmark, geen bindend aanbod.',
    servicesTitle: 'European Shortsea Support',
    servicesText: 'Onafhankelijke validatie en besluitvorming voor intra-Europees droge bulk en stukgoed vervoer.',
    service1Title: 'Spot Chartering Inzicht',
    service1Text: 'Objectieve validatie van losse reis-offertes tussen alle Europese havens.',
    service2Title: 'COA Analyse',
    service2Text: 'Kosten- en risicoanalyse voor lange-termijn volumecontracten.',
    service3Title: 'Projectlading Validatie',
    service3Text: 'Gespecialiseerde review voor zware of buitenmaatse transporten.',
    service4Title: 'Compliance & Blootstelling',
    service4Text: 'Monitoring van internationale normen en milieukosten-modellering.',
    service5Title: 'Logistieke Risico-Check',
    service5Text: 'Beoordeling van operationele knelpunten in shortsea-routes.',
    serviceFreightTitle: 'Vracht Benchmarking',
    serviceFreightText: 'Data-gestuurde vrachtindicaties om de marktwaarde van uw route te bepalen.',
    serviceAnalyzerTitle: 'Offerte Validatie',
    serviceAnalyzerText: 'Professionele risico- en commerciële analyse van broker-offertes.',
    servicesCtaTitle: 'Versterk uw chartering-positie.',
    servicesCtaText: 'Krijg toegang tot objectieve data om uw bevrachtingsvoorwaarden te verbeteren.',
    servicesCtaButton: 'Neem Contact Op',
    insightsTitle: 'Advisering & Marktdata',
    insightsText: 'Valideer ontvangen offertes, monitor risico-exposures en volg onafhankelijke marktbenchmarks.',

    // Homepage Strategy Scan Dashboard
    targetRateTitle: 'Charterer Richtprijs (PMT)',
    idealFixingTarget: 'Ideaal Fixdoel',
    idealFixingDesc: 'Streef naar dit tarief voor de beste commerciële balans.',
    costTransparency: 'Kostentransparantie (PMT)',
    marketBaseRate: 'Markt Basistarief',
    bunkerFactor: 'Bunker Factor',
    liveBunkerBench: 'Live LSMGO Benchmark',
    externalFactors: 'Externe Factoren',
    weatherSeasonal: 'Weer/Seizoen',
    portCanalFees: 'Haven- & Kanaalkosten',
    totalPmtEstimate: 'TOTAAL PMT INDICATIE',
    strategyAdvice: 'Strategisch Charter-Advies',
    co2Threshold: 'CO2 Grenswaarde',
    routeStatus: 'Route Status',
    trend30Days: '30-Dagen Trend',
    lastMatch: 'Laatste match',
    yourLeverage: 'Uw Voordeel',
    negotiationDesk: 'Charterer Onderhandelingstafel',
    tacticalPushback: 'Tactische Argumenten',
    estVoyage: 'Verw. Reisduur',
    seaDistance: 'Zee-afstand',
    shortest: 'KORTSTE',
    noCanal: 'GEEN KANAAL',
    viaKiel: 'Via Kiel Kanaal',
    viaSkagen: 'Via Skagen',
    recalculateRoute: 'Benchmark Actualiseren',
    exportStrategy: 'Exporteer Strategie',

    // Homepage New Content
    vp1Title: 'OFFERTE VALIDATE',
    vp1Text: 'Stuur uw offerte in voor onafhankelijke risico-review. Wij controleren voorwaarden, prijs en marktconformiteit.',
    vp2Title: 'MARKT BENCHMARKING',
    vp2Text: 'Toegang tot objectieve tarieven en historische data. Zie wat redelijk is voor uw specifieke route.',
    vp3Title: 'DATA-GEBASEERD ONDERHANDELEN',
    vp3Text: 'Onderhandel met concrete argumenten om uw commerciële bevrachtingsvoorwaarden te verbeteren.',
    vp4Title: 'PUUR ONAFHANKELIJK',
    vp4Text: 'Wij zijn geen broker en innen geen commissie. Ons inzicht is 100% objectief.',
    
    processTitle: 'Validatie in 3 Stappen',
    step1HomeTitle: 'Ontvang een Offerte',
    step1HomeDesc: 'Vraag een aanbod aan bij uw broker voor een coaster of minibulker.',
    step2HomeTitle: 'Wij Valideren',
    step2HomeDesc: 'Upload the details voor een onafhankelijke commerciële- en risicoanalyse.',
    step3HomeTitle: 'Fix met Zekerheid',
    step3HomeDesc: 'Neem uw uiteindelijke besluit onderbouwd door onafhankelijke marktdata.',

    // Advisory UI
    advTabTrends: 'Marktbenchmarks',
    advTabAnalyzer: 'Offerte Analyzer',
    advTabDocs: 'Standaard Bescheiden',
    advAnalyzerTitle: 'Professionele Offerte Validatie',
    advAnalyzerSubtitle: 'Commerciële- en risico-review van ontvangen offertes. Wij werken onafhankelijk van brokerage commissies.',
    advAnalyzerPlaceholder: 'Plak de tekst van de broker offerte hier (bijv. scheepsnaam, tarief, laycan, condities)...',
    advAnalyzerPricingNote: 'Validatiediensten worden geleverd tegen vaste tarieven. Wij innen geen brokerage commissie.',
    advUploadPdf: 'Upload PDF Offerte',
    advFileSelected: 'PDF Bijgevoegd: ',
    advOptionA: 'AI-Snelscan',
    advOptionADesc: 'Directe data-gestuurde validatie. Vaste vergoeding per scan.',
    advOptionB: 'Expert-Beoordeling',
    advOptionBDesc: 'Diepgaande handmatige review door ervaren bevrachters. Vaste vergoeding.',
    advBtnAnalyze: 'Start Validatie-Scan',
    advBtnExpert: 'Verzend voor Expert-Review',
    advSuccessPending: 'Aanvraag ingediend voor expert-validatie. Wij bemiddelen niet bij de fix; resultaten zijn puur ondersteunend.',
    miUpdateBtn: 'Haal Laatste Benchmarks Op',
    
    // Gatekeeping & CTA
    advRegisterToView: 'Meld u gratis aan om het volledige rapport te bekijken',
    advUpgradePro: 'Upgrade naar Professioneel voor onbeperkte uitgebreide scans',
    advMonthlyLimit: 'Maandelijkse limiet voor gratis rapporten bereikt',

    // Tile Labels
    tileAvgFreight: 'Markt Gem.',
    tileAvailability: 'Scheepsaanbod',
    tileDeepDive: 'Expert Analyse',
    regionBaltic: 'Baltische Zee',
    regionNorthSea: 'Noordzee / UKC',
    regionMed: 'Middellandse Zee',
    regionBlackSea: 'Zwarte Zee',

    // Regional Highlights (Translations)
    hlBaltic1: 'IJs-restricties monitoring actief in Kemi.',
    hlBaltic2: 'Baltische graan-export exposure neemt toe.',
    hlNorthSea1: 'Congestie-alerts voor grote UKC hubs.',
    hlNorthSea2: 'Staal-vraag validatie stabil.',
    hlMed1: 'Hoge activiteit in havens Oostelijke Med.',
    hlMed2: 'Bunker exposure monitoring for Algeciras.',
    hlBlackSea1: 'Risicopremie validatie vereist.',
    hlBlackSea2: 'Operationele stabiliteit monitoring Constanta.',

    // Trend Labels
    trendStable: 'Stabiel',
    trendFirm: 'Stijgend',
    trendSoft: 'Dalend',

    // Trial
    trialRemaining: 'Nog {{days}} dagen proefperiode',
    trialExpired: 'Proefperiode verlopen - Krijg Professional Inzicht',

    // How It Works
    hiwTitle: 'Het Validatieproces',
    hiwSubtitle: 'Onafhankelijke besluitvorming, simpel en transparant.',
    step1Title: 'Indiceren',
    step1Desc: 'Voer ladinggegevens in voor een initiële marktbenchmark.',
    step2Title: 'Analyseren',
    step2Desc: 'Gebruik tools om operationele- en routerisico\'s te bepalen.',
    step3Title: 'Valideren',
    step3Desc: 'Stuur uw offerte in voor een onafhankelijke AI of Expert review.',
    step4Title: 'Fixen',
    step4Desc: 'Sluit uw deal met uw broker, onderbouwd door objectieve data.',
    hiwCta: 'Start Benchmarking',

    // Contact
    contactTitle: 'Inquiry Desk',
    contactIntro: 'Neem contact op voor gespecialiseerde validatie of account-vragen.',
    contactHq: 'Operations',
    contactPhone: 'Inquiry Lijn',
    contactEmail: 'E-mail',
    contactFormTitle: 'Stuur een Bericht',
    formFirstName: 'Voornaam',
    formFirstNamePlaceholder: 'Jan',
    formLastName: 'Achternaam',
    formLastNamePlaceholder: 'Jansen',
    formCompany: 'Bedrijf',
    formEmail: 'E-mailadres',
    formMessage: 'Aanvraag Details',
    formSend: 'Bericht Verzenden',

    // Request Offer
    roTitle: 'Expert-Validatie Aanvraag',
    roSubtitle: 'Voer de reisgegevens in voor een onafhankelijk professioneel validatierapport.',
    roSuccess: 'Aanvraag ontvangen. Onze experts analyseren uw dossier onafhankelijk van broker-belangen.',
    roSectionVoyage: 'Reisgegevens',
    roLaycanStart: 'Laycan Start',
    roLaycanEnd: 'Laycan Eind',
    roSectionCargo: 'Ladingspecificaties',
    roStowage: 'Stuwagefactor',
    roHazmat: 'Speciale Vereisten',
    roSectionTerms: 'Voorwaarden',
    roSectionContact: 'Contactgegevens',
    roTerms: 'Bevrachtingsvoorwaarden',
    roIdea: 'Doeltarief voor Validatie',
    roSubmit: 'Vraag Professioneel Rapport Aan',

    // Pricing
    pricingTitle: 'Accountvormen',
    pricingSubtitle: 'Objectiviteit is onze kracht. Wij bieden onafhankelijk inzicht zonder brokerage commissies.',
    planFree: 'Standaard Toegang',
    mo: '/ mnd',
    feat1: 'Gelimiteerde reisindicaties',
    feat2: 'Basis marktbenchmarks',
    feat3: 'Standaard operationele tools',
    feat4: 'Onbeperkt benchmarken',
    feat5: 'Volledige besluitvormings-toolkit',
    feat6: 'Premium regionale marktintel',
    feat7: 'Strategische supportdesk',
    feat8: 'Enterprise integraties',
    featAiScanPay: 'AI-Snelscan: €15,- per check (Pay-per-scan)',
    featNoExpert: 'Geen toegang tot Expert-beoordeling',
    featAiScanUnlim: 'Onbeperkte AI-Snelscans (Inbegrepen t.w.v. €15 per scan)',
    featExpertAddon: 'Expert-Beoordeling Add-on: €195,- per check (Gereduceerd tarief)',
    featExpertIncl: 'Inclusief 2 Expert-beoordelingen per maand',
    featExpertPriority: 'Prioriteit bij handmatige dossier-reviews',
    pricingSaveBadge: 'Bespaar direct: De AI-Snelscan valideert uw broker-offertes op marktconformiteit en risico’s. Professionele gebruikers scannen onbeperkt zonder extra kosten.',
    btnStart: 'Toegang Activeren',
    btnContact: 'Neem Contact Op',
    planPro: 'Professioneel',
    planEnt: 'Enterprise',

    // About
    aboutTitle: 'Shortsea Europe Onafhankelijkheid',
    aboutSubtitle: 'Transparantie herstellen in de maritieme markt door objectieve validatie.',
    abPartnerTitle: 'WAAROM SHORTSEA EUROPE?',
    abReliablePartnerTitle: 'Uw Betrouwbare Partner',
    abReliablePartnerText: 'Na meer dan 20 jaar als bevrachter te hebben gewerkt, ken ik uit de eerste hand de behoefte aan praktische, onafhankelijke tools voor ladingeigenaren. Ik heb Shortsea Europe opgericht om dit bekersysteem te dichten en u te helpen effectiever te communiceren met uw broker. Ons platform stelt u in staat om aanbiedingen en adviezen objectief te valideren, waarbij u de data en tegenargumenten krijgt die nodig zijn om uw positie te versterken. Navigeer met vertrouwen door uw onderhandelingen, ondersteund door professioneel inzicht.',
    abBullet1: 'Gedreven door Master Mariners',
    abBullet2: 'Onafhankelijk & Transparant',
    abBullet3: 'Volledige Digitale Integratie',
    abImp1: 'Betere Condities',
    abImp2: 'Beperkt Risico',
    abImp3: 'Tarieven Precisie',
    aboutTitle_full: 'Over Shortsea Europe',
    abWhatIsTitle: 'Kernwaarden',
    abWhatIsText: 'Objectiviteit en transparantie vormen de kern van ons platform.',
    abWhatIs1: 'Onafhankelijkheid: Geen brokerage commissies.',
    abWhatIs2: 'Validatie: Data-gestuurde offertescans.',
    abWhatIs3: 'Inzicht: Objectieve regionale trends.',
    abWhatIs4: 'Integriteit: In dienst van de verlader.',
    abAiTitle: 'Data-Gestuurd',
    abAiText: 'Gebruik van algoritmen voor real-time markttrends.',
    abProcessTitle: 'Objectieve Review',
    abProcessText: 'Van indicatie naar validatie zonder belangenverstrengeling.',
    abSafeTitle: 'Veilig & Conform',
    abSafeText: 'Onafhankelijk getoetst aan EU milieu- en dataregels.',
    abGreenTitle: 'Duurzaam Inzicht',
    abGreenText: 'Objectieve inschatting van milieu-exposures en ETS-kosten.',

    // Tools
    toolDist: 'Afstand Engine',
    toolDistDesc: 'Standaard maritieme zeeafstanden voor planning.',
    toolStow: 'Stuwage Utility',
    toolStowDesc: 'Indicatieve conversie van stuwagefactoren.',
    toolLay: 'Ligtijd Utility',
    toolLayDesc: 'Onafhankelijke berekening van afwikkelingsrisico\'s.',
    toolIce: 'IJs-restrictie Monitor',
    toolIceDesc: 'Indicatieve ijs-status voor Baltische planning.',
    toolDA: 'Havenkosten (D/A)',
    toolETS: 'ETS Exposure Monitor',
    toolETSDesc: 'Indicatieve CO2-kostenbeoordeling voor EU-havens.',
    toolsTitle: 'Besluitvormingstools',
    toolsSubtitle: 'Indicatieve berekeningstools ter ondersteuning van Europese shortsea-professionals.',
    btnUse: 'Open Tool',
    trustedBy: 'Onafhankelijk inzicht voor Europese chartering-professionals',

    // Compliance
    compTitle: 'Standaarden & Integriteit',
    compSubtitle: 'Onze toewijding aan data-objectiviteit en regelgeving.',
    compIntro: 'Shortsea Europe handhaaft absolute onafhankelijkheid van reders en brokers om onbevooroordeelde besluitvorming te garanderen.',
    compGdprTitle: 'Data Integriteit',
    compGdpr1: 'Encryptie voor alle bevrachtingsgegevens.',
    compGdpr2: 'Geen verstrekking van aanvragen aan commerciële derden.',
    compGdpr3: 'Gebruikerscontrole over alle opgeslagen validatiehistorie.',
    compMarTitle: 'Regelgeving',
    compMar1: 'EU MRV rapportage benchmarks.',
    compMar2: 'Objectieve EU ETS kostenmodellering.',
    compMar3: 'BIMCO standaard clausule monitoring.',
    compDigTitle: 'Platform Betrouwbaarheid',
    compDig1: 'Beveiligde toegangsprotocollen.',
    compDig2: 'Regelmatige onafhankelijke audits.',
    compDig3: 'Betrouwbare marktdatabronnen.',
    compEnvTitle: 'Milieubeoordeling',
    compEnv1: 'Indicatieve emissiemodellering.',
    compEnv2: 'Bunker efficiency benchmarks.',
    compEnv3: 'Green corridor exposure tracking.',
    compFooter: 'Systemen worden bijgewerkt om de nieuwste Europese maritieme regelgeving te reflecteren.',

    // Cookie Settings
    cookieTitle: 'Cookie-instellingen',
    cookieIntro: 'Shortsea Europe gebruikt cookies and vergelijkbare technologieën (zoals localStorage) om de functionaliteit van het platform te waarborgen en uw gebruikerservaring te verbeteren.',
    cookieFuncTitle: 'Functionele Technologieën (Noodzakelijk)',
    cookieFuncText: 'Wij gebruiken lokale opslag om de resultaten van marktscans en route-indicaties (zoals routes van Tartous naar Luleå) op uw Chartering Advisory pagina te bewaren. Zonder deze technologie zouden gegevens bij elke paginalading verdwijnen.',
    cookieAnalyticTitle: 'Analytische Cookies',
    cookieAnalyticText: 'Wij kunnen geanonimiseerde statistieken bijhouden over hoe onze tools worden gebruikt om de snelheid en nauwkeurigheid van onze AI-modellen (Gemini Pro/Flash) te verbeteren.',
    cookieManageTitle: 'Beheer',
    cookieManageText: 'U kunt via deze instellingen of via uw browserinstellingen bepalen welke cookies u accepteert. Let op: het uitschakelen van functionele cookies kan leiden tot het verlies van opgeslagen berekeningen op uw dashboard.',
    cookieEprivacyTitle: 'Cookiebeleid & Transparantie',
    cookieStrictTitle: 'Strikte Noodzakelijkheid',
    cookieStrictText: 'Wij gebruiken localStorage voor het onthouden van uw "Chartering Advisory" data na een handmatige scan door de Admin. Volgens de EU ePrivacy-richtlijn is voor deze functionele opslag geen voorafgaande toestemming vereist, mits deze essentieel is voor de door de gebruiker gevraagde dienst.',
    cookieNoTrackTitle: 'Geen Tracking van Derden',
    cookieNoTrackText: 'Shortsea Europe verkoopt uw zoekgedrag (zoals trajecten van Tartous naar Luleå) niet door aan advertentienetwerken van derden.',
    cookiePrefTitle: 'Beheer van Voorkeuren',
    cookiePrefText: 'Gebruikers kunnen hun voorkeuren voor analytische tools op elk moment aanpassen via dit menu.',

    // Privacy Policy
    privacyTitle: 'Privacybeleid - Shortsea Europe',
    privacyIntro: 'Bij Shortsea Europe nemen wij de bescherming van uw gegevens serieus. Dit privacybeleid legt uit hoe wij omgaan met informatie op onze Chartering Advisory pagina en andere onderdelen van ons platform.',
    privacyCollTitle: 'Gegevensverzameling',
    privacyCollText: 'Wij verzamelen uitsluitend gegevens die noodzakelijk zijn voor het genereren van maritieme adviezen, zoals laad-/loshavens, ladingtypes en volumes.',
    privacyAiTitle: 'Gebruik van AI en Data',
    privacyAiText: 'Onze website maakt gebruik van geavanceerde AI-modellen en websearch-technologie om live marktdata, bunkerprijzen en navigatieroutes te analyseren. Deze data wordt gebruikt om de gebruiker te voorzien van intelligente marktinzichten.',
    privacyStoreTitle: 'Opslag van Gegevens',
    privacyStoreText: 'Voor uw gebruiksgemak maken wij gebruik van lokale opslag (localStorage) in uw browser. Dit zorgt ervoor dat de laatste marktanalyses en routeberekeningen zichtbaar blijven op uw scherm, ook na het verversen van de pagina, tot er een nieuwe scan wordt uitgevoerd door de administrator.',
    privacySecTitle: 'Beveiliging',
    privacySecText: 'Wij implementeren strikte technische maatregelen om ongeautoriseerde toegang tot onze systemen en uw zoekgeschiedenis te voorkomen.',
    privacyRightsTitle: 'Rechten van Gebruikers',
    privacyRightsText: 'U heeft het recht om uw lokale browsergegevens te wissen via uw browserinstellingen.',
    privacyGdprTitle: 'AVG / GDPR Verklaring',
    privacyGdprLegalTitle: 'Rechtsgrondslag',
    privacyGdprLegalText: 'Wij verwerken gegevens op basis van het gerechtvaardigd belang voor de uitvoering van maritieme analyses en offertes.',
    privacyGdprAccessTitle: 'Recht op Inzage en Verwijdering',
    privacyGdprAccessText: 'Conform de EU-wetgeving heeft u het recht om uw gegevens in te zien, te corrigeren of te laten verwijderen uit onze lokale systemen.',
    privacyGdprEuStorageTitle: 'Gegevensopslag binnen de EU',
    privacyGdprEuStorageText: 'Wij streven naar gegevensverwerking zoveel mogelijk binnen de Europese Economische Ruimte (EER). Waar AI-modellen buiten de EER worden gebruikt, geschiedt dit onder strikte beveiligingsprotocollen.',
    privacyGdprAutoTitle: 'Geautomatisede Besluitvorming',
    privacyGdprAutoText: 'Onze website maakt gebruik van algoritmen voor marktcijfers zoals "Market Avg" en "Vessel Supply". Deze zijn uitsluitend indicatief en vormen geen juridisch bindend geautomatiseerd besluit.',

    // EU Compliance Page
    euCompTitle: 'EU Compliance & Regelgeving',
    euCompIntro: 'Shortsea Europe zet zich volledig in voor het naleven van de Europese regelgeving, waaronder de AVG/GDPR en de ePrivacy-richtlijnen.',

    // Legal Disclaimer
    legalDisclaimerTitle: 'MARITIME DISCLAIMER (EU COMPLIANT)',
    legalDisclaimerText: 'De getoonde routes, inclusief het Skagen-alternatief (stippellijn), zijn AI-gegenereerde simulaties voor commerciële analysedoeleinden. Deze data voldoet niet aan de eisen van SOLAS/IMO voor navigatie. Gebruik voor navigatie is strikt verboden en geschiedt op eigen risico. Shortsea Europe aanvaardt geen aansprakelijkheid voor nautische incidenten of financiële verliezen voortvloeiend uit het gebruik van deze informatie.',

    // Terms of Service
    tosTitle: 'Terms and Service - Shortsea Europe',
    tos1Title: '1. Acceptatie van de Voorwaarden',
    tos1Text: 'Door gebruik te maken van de website en de diensten van Shortsea Europe, verklaart u zich akkoord met deze Algemene Voorwaarden. Deze voorwaarden zijn van toepassing op alle gebruikers, inclusief charterers, reders en cargohouders.',
    tos2Title: '2. Informatieve Dienstverlening (Geen Garantie)',
    tos2Text: 'Shortsea Europe biedt logistieke intelligentie, vrachtprijsindicaties en navigatieroutes aan op basis van kunstmatige intelligentie (AI) en externe marktdata. Alle verstrekte gegevens (inclusief vrachtprijzen, brandstofkosten, ETS-berekeningen en routes) zijn uitsluitend bedoeld voor informatieve doeleinden. Shortsea Europe garandeert op geen enkele wijze de juistheid, volledigheid of actualiteit van de verstrekte informatie. Gebruik van deze data is volledig voor eigen risico van de gebruiker.',
    tos3Title: '3. Uitsluiting van Aansprakelijkheid (Vrijwaring)',
    tos3Text: 'Shortsea Europe, haar eigenaren en medewerkers kunnen onder geen beding aansprakelijk worden gesteld voor: Navigatiefouten, Financieel verlies, of Operationele vertragingen.',
    tos3NavTitle: 'Navigatiefouten',
    tos3NavText: 'Hoewel onze systemen zijn geprogrammeerd om veilige maritieme routes te simuleren, dienen deze nooit te worden gebruikt voor feitelijke navigatie aan boord. De uiteindelijke routeplanning is de exclusieve verantwoordelijkheid van de gezagvoerder (Master) en de rederij.',
    tos3FinTitle: 'Financieel verlies',
    tos3FinText: 'Wij zijn niet aansprakelijk voor indirecte schade, gevolgschade, gederfde winst of gemiste besparingen die voortvloeien uit beslissingen genomen op basis van onze marktcijfers of adviezen.',
    tos3OpTitle: 'Operationele vertragingen',
    tos3OpText: 'Wij aanvaarden geen aansprakelijkheid voor kosten voortvloeiend uit ijsrestricties, havencongestie of kanaalpassages die afwijken van onze indicaties.',
    tos4Title: '4. Intellectueel Eigendom',
    tos4Text: 'De unieke software-architectuur, route-logica en interface van Shortsea Europe zijn eigendom van de website-eigenaar. Het kopiëren, reverse-engineeren of onrechtmatig verspreiden van onze data en code is strikt verboden.',
    tos5Title: '5. Wijzigingen en Beschikbaarheid',
    tos5Text: 'Shortsea Europe behoudt zich het recht voor om de dienstverlening op elk moment te wijzigen of te staken zonder voorafgaande kennisgeving. Wij zijn niet aansprakelijk voor technische storingen of tijdeloonbeschikbaarheid van de website.',
    tos6Title: '6. Toepasselijk Recht',
    tos6Text: 'Op deze voorwaarden en alle geschillen die voortvloeien uit het gebruik van Shortsea Europe is het Nederlands recht van toepassing. Geschillen zullen uitsluitend worden voorgelegd aan de bevoegde rechter in het arrondissement waar de eigenaar van de website is gevestigd.',

    // Standard texts
    freightIndicationTitle: 'VRACHTPRICE BENCHMARK (PMT)',
    lowEstimate: 'MARKT LAAG',
    highEstimate: 'MARKT HOOG',
    estimateDisclaimer: 'Indicaties zijn marktbenchmarks ter ondersteuning.',
    proceedToFirm: 'VALIDEER UW ONTVANGEN OFFERTE',
    reqFirmOffer: 'Vraag Validatierapport Aan',
    calculationBasis: 'Gebaseerd op onafhankelijke marktgemiddelden.',
    prop1Title: 'Snelle Validatie',
    prop1Text: 'Vaststellen van benchmarks in seconden.',
    prop2Title: 'Onafhankelijke Data',
    prop2Text: 'Gedistilleerd uit geverifieerde fixtures en bunkerdata.',
    prop3Title: 'Objectief Netwerk',
    prop3Text: 'Dekking over het gehele Europese coaster-aanbod.',
    prop4Title: 'Integriteits-Garantie',
    prop4Text: 'Absolute onafhankelijkheid van brokers en commissies.',
    ctaSecondary_nav: 'Advies Aanvragen',
    footerText: 'Onafhankelijke besluitvorming voor de moderne verlader.',
    footerPlatform: 'Platform',
    footerCompany: 'Operations',
    footerServices: 'Validatie',
    footerInsights: 'Market Intel',
    footerPricing: 'Toegang',
    footerAbout: 'Onafhankelijkheid',
    footerContact: 'Inquiry',
    footerRights: 'Alle rechten voorbehouden.',
    miRegional: 'Regionale Intel',
    miBunkers: 'Bunker Benchmarks',
    miCargo: 'Lading Indicatoren',
    miLastUpdate: 'Benchmark Sync',
    miDriver: 'Primaire Marktdrijver',

    // Dashboard Keys
    dbWelcome: 'Welkom terug, {{name}}',
    dbSummary: 'U heeft {{msgCount}} berichten en {{advCount}} actieve dossiers.',
    dbNewScan: 'Nieuwe AI Scan',
    dbReqAdvice: 'Vraag Expert Advies',
    dbReqExpert: 'Vraag Expert Review',
    dbTotalScans: 'Totaal AI Scans',
    dbExpertReports: 'Expert Rapporten',
    dbHqMessages: 'HQ Berichten',
    dbRecentScans: 'Recente Scans',
    dbViewAll: 'Bekijk Alles',
    dbNoScans: 'Geen recente scans.',
    dbHqNotifs: 'HQ Notificaties',
    dbInbox: 'Inbox',
    dbNoMsgs: 'Geen nieuwe berichten.',
    dbScanHist: 'AI Validatie Historie',
    dbScanHistDesc: 'Overzicht van alle AI Quick Scans uitgevoerd op dit account.',
    dbColDate: 'Datum',
    dbColQuote: 'Offerte / Referentie',
    dbColStatus: 'Status',
    dbColAction: 'Actie',
    dbStatusComp: 'Voltooid',
    dbViewAdvice: 'Bekijk Advies',
    dbExpertDossiers: 'Expert Dossiers',
    dbNoDossiers: 'Geen dossiers.',
    dbCharterAdvice: 'Bevrachtingsadvies',
    dbDossier: 'Dossier',
    dbReviewProgress: 'Expert Review in Behandeling',
    dbReviewDesc: 'Onze brokers analyseren uw offerte tegen actuele marktdata. U ontvangt bericht zodra het advies is vrijgegeven.',
    dbHqDash: 'HQ Advisory Dashboard',
    dbSelectDossier: 'Selecteer een dossier uit de zijbalk voor gedetailleerde expertanalyse en marktrisico\'s.',
    dbHqComm: 'HQ Communicatiecentrum',
    dbHqCommDesc: 'Directe berichten en systeemupdates van Shortsea Europe HQ.',
    dbInboxEmpty: 'Inbox Leeg',
    dbAccountMember: 'Account Lid',
    dbCompany: 'Bedrijfsnaam',
    dbEmail: 'E-mailadres',
    dbMemberSince: 'Lid Sinds',
    dbVerifyStatus: 'Verificatie Status',
    dbVerified2fa: 'Geverifieerd 2FA',
    dbEncryptedNote: 'Persoonlijke profielgegevens zijn versleuteld volgens Shortsea Pro protocollen. Neem contact op met HQ om bedrijfsgegevens te wijzigen.',
    dbTerminate: 'Sessie Beëindigen',
    dbPortalTitle: 'Client Portal',
    dbPortalSubtitle: 'Shortsea Europe Control',
    dbSignOut: 'Uitloggen',
    dbArchiveTitle: 'AI Quick Scan Archief',
    dbRef: 'Referentie',
    dbOrigQuote: 'Originele Offerte Invoer',
    dbCloseArchive: 'Sluit Archief',
    dbNavOverview: 'Overzicht',
    dbNavScans: 'AI Scans',
    dbNavAdvisory: 'Advisory',
    dbNavMessages: 'HQ Berichten',
    dbNavProfile: 'Account Profiel'
  },
};
